#!/usr/bin/env node
/**
 * Generates the favicon set from one vector description of the S.I.L.K
 * spider: public/favicon.svg, plus PNG fallbacks (32 px favicon and 180 px
 * Apple touch icon) rasterized here with a tiny supersampling renderer, so
 * no image tool or third-party asset is needed.
 *
 *   npm run icons
 */
import { writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';

const BG = '#05070b';
const LEG = '#e8f6ff';
const CYAN = '#5ee6ff';
const PINK = '#ff3d7f';

/** The spider hangs head-down from its thread, in a 32x32 box. */
const left = [
  // From the cephalothorax, through the knee, to the foot.
  [[14.4, 20.6], [10.2, 23.6], [8.4, 29]],
  [[14, 19.6], [8.6, 20.2], [4.4, 24.4]],
  [[14, 18.4], [8.4, 15.8], [4.2, 17.2]],
  [[14.4, 17.4], [10.4, 12.6], [7, 8.8]],
];
const legs = [...left, ...left.map((leg) => leg.map(([x, y]) => [32 - x, y]))];

const shapes = [
  { type: 'rect', x: 0, y: 0, w: 32, h: 32, r: 7, fill: BG },
  { type: 'line', points: [[16, 0], [16, 8]], width: 1, stroke: LEG, opacity: 0.55 },
  ...legs.map((points) => ({ type: 'line', points, width: 1.7, stroke: LEG })),
  { type: 'ellipse', cx: 16, cy: 12.6, rx: 4.2, ry: 5, fill: BG, stroke: CYAN, width: 1.4 },
  { type: 'ellipse', cx: 16, cy: 19.6, rx: 2.9, ry: 2.6, fill: BG, stroke: CYAN, width: 1.4 },
  { type: 'circle', cx: 16, cy: 12.6, r: 1.7, fill: PINK },
  { type: 'circle', cx: 15, cy: 20.6, r: 0.75, fill: CYAN },
  { type: 'circle', cx: 17, cy: 20.6, r: 0.75, fill: CYAN },
];

// ------------------------------------------------------------------ SVG

function toSvg() {
  const body = shapes
    .map((s) => {
      switch (s.type) {
        case 'rect':
          return `<rect width="${s.w}" height="${s.h}" rx="${s.r}" fill="${s.fill}"/>`;
        case 'line':
          return `<polyline points="${s.points.map((p) => p.join(',')).join(' ')}" fill="none" stroke="${s.stroke}" stroke-width="${s.width}" stroke-linecap="round" stroke-linejoin="round"${s.opacity ? ` stroke-opacity="${s.opacity}"` : ''}/>`;
        case 'ellipse':
          return `<ellipse cx="${s.cx}" cy="${s.cy}" rx="${s.rx}" ry="${s.ry}" fill="${s.fill}" stroke="${s.stroke}" stroke-width="${s.width}"/>`;
        case 'circle':
          return `<circle cx="${s.cx}" cy="${s.cy}" r="${s.r}" fill="${s.fill}"/>`;
      }
    })
    .join('\n  ');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">\n  <!-- S.I.L.K spider, generated by scripts/generate-icons.mjs -->\n  ${body}\n</svg>\n`;
}

// ------------------------------------------------------------ rasterizer

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 3 - 1), 16));

function distanceToSegment(px, py, [ax, ay], [bx, by]) {
  const dx = bx - ax;
  const dy = by - ay;
  const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy || 1)));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

/** Colour (or null) a shape paints at a point, as [rgb, alpha]. */
function paint(s, x, y) {
  switch (s.type) {
    case 'rect': {
      const qx = Math.max(s.r - x, 0, x - (s.w - s.r));
      const qy = Math.max(s.r - y, 0, y - (s.h - s.r));
      return Math.hypot(qx, qy) <= s.r ? [rgb(s.fill), 1] : null;
    }
    case 'line': {
      for (let i = 1; i < s.points.length; i++) {
        if (distanceToSegment(x, y, s.points[i - 1], s.points[i]) <= s.width / 2) return [rgb(s.stroke), s.opacity ?? 1];
      }
      return null;
    }
    case 'ellipse': {
      // Normalized radial distance; stroke straddles the outline.
      const d = Math.hypot((x - s.cx) / s.rx, (y - s.cy) / s.ry);
      const r = Math.min(s.rx, s.ry);
      const edge = (d - 1) * r;
      if (Math.abs(edge) <= s.width / 2) return [rgb(s.stroke), 1];
      return d < 1 ? [rgb(s.fill), 1] : null;
    }
    case 'circle':
      return Math.hypot(x - s.cx, y - s.cy) <= s.r ? [rgb(s.fill), 1] : null;
  }
  return null;
}

function rasterize(size, samples = 6) {
  const scale = 32 / size;
  const pixels = new Uint8Array(size * size * 4);
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let sy = 0; sy < samples; sy++) {
        for (let sx = 0; sx < samples; sx++) {
          const x = (px + (sx + 0.5) / samples) * scale;
          const y = (py + (sy + 0.5) / samples) * scale;
          let color = null;
          let alpha = 0;
          for (const shape of shapes) {
            const hit = paint(shape, x, y);
            if (!hit) continue;
            const [c, o] = hit;
            color = color ? color.map((v, i) => v * (1 - o) + c[i] * o) : c;
            alpha = alpha + o * (1 - alpha);
          }
          if (color) {
            r += color[0];
            g += color[1];
            b += color[2];
            a += alpha;
          }
        }
      }
      const n = samples * samples;
      const i = (py * size + px) * 4;
      const coverage = a / n;
      pixels[i] = coverage ? r / (coverage * n) : 0;
      pixels[i + 1] = coverage ? g / (coverage * n) : 0;
      pixels[i + 2] = coverage ? b / (coverage * n) : 0;
      pixels[i + 3] = Math.round(coverage * 255);
    }
  }
  return pixels;
}

// ------------------------------------------------------------------ PNG

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function png(size, pixels) {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // RGBA
  const raw = Buffer.alloc((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0; // no filter
    Buffer.from(pixels.buffer, y * size * 4, size * 4).copy(raw, y * (size * 4 + 1) + 1);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const out = new URL('../public/', import.meta.url);
writeFileSync(new URL('favicon.svg', out), toSvg());
writeFileSync(new URL('favicon-32.png', out), png(32, rasterize(32)));
writeFileSync(new URL('apple-touch-icon.png', out), png(180, rasterize(180, 3)));
console.log('Icons written to public/');
